version: "3.2"
services:
  docs:
    image: ghcr.io/codex-team/codex.docs:v2.0.0-rc.8
    ports:
      - "3000:3000"
    volumes:
      # - ./locales:/usr/src/app/locales
      - ./uploads:/usr/src/app/uploads
      - ./db:/usr/src/app/db
      - ./docs-config.local.yaml:/usr/src/app/docs-config.yaml
